mvc/Controllers/CerrarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc.Controllers
{
    public class CerrarController : Controller
    {
        // GET: Cerrar
        public ActionResult Logoff()
        {
            Session["Usuario"] = null;

            return RedirectToAction("Index","acceder");
        }
    }
}

mvc/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


using mvc.Models;
using mvc.Models.TableVewModel;

using mvc.Models.ViewModels;
namespace mvc.Controllers
{
    public class VehiculoController : Controller
    {
        // GET: Vehiculo
        public ActionResult Index()
        {
            List<VehiculoTableViewModel> lst = null;

            using (DBVEHICULOSEntities db = new DBVEHICULOSEntities())
            {
                lst = (from d in db.VEHICULO
                       orderby d.ID
                       
                       select new VehiculoTableViewModel
                       {
                           ID = d.ID,
                           Marca = d.MARCA,
                           Modelo = d.MODELO,
                           Año = d.nYEAR,
                           Condicion = d.CONDICION,
                           Imagen = d.FOTOS
                       }).ToList();
            }



            return View(lst);
        }

        [HttpGet]
        public ActionResult Add()
        {


            return View();
        }

        [HttpPost]
        public ActionResult  Add(VehiculoViewModel model)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(model);
            //}
            using(var db = new DBVEHICULOSEntities())
            {
                VEHICULO oVehiculo = new VEHICULO();
                oVehiculo.MARCA = model.Marca;
                oVehiculo.MODELO = model.Modelo;
                oVehiculo.nYEAR = model.Año;
                oVehiculo.CONDICION = model.Condicion;
                oVehiculo.FOTOS = model.Foto;
                

                db.VEHICULO.Add(oVehiculo);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Vehiculo/"));
        }

        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EditVehiculoViewModel model = new EditVehiculoViewModel();
            using(var db = new DBVEHICULOSEntities())
            {
                var oVehiculo = db.VEHICULO.Find(Id);
                model.Marca = oVehiculo.MARCA;
                model.Modelo = oVehiculo.MODELO;
                model.Año = oVehiculo.nYEAR;
                model.Condicion = oVehiculo.CONDICION;
                model.Foto = oVehiculo.FOTOS;
            }

            return View(model) ;
        }

        [HttpPost]
        public ActionResult Edit(EditVehiculoViewModel model)
        {
            using(var db = new DBVEHICULOSEntities())
            {
                var oVehiculo = db.VEHICULO.Find(model.ID);
                oVehiculo.MARCA = model.Modelo;
                oVehiculo.MODELO = model.Modelo;
                oVehiculo.nYEAR = model.Año;
                oVehiculo.CONDICION = model.Condicion;
                oVehiculo.FOTOS = model.Foto;

                db.Entry(oVehiculo).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Redirect(Url.Content("~/Vehiculo/"));
            }

            
        }

        [HttpPost]
        public ActionResult Delete(int Id)
        {
            using (var db = new DBVEHICULOSEntities())
            {
                var oVehiculo = db.VEHICULO.Find(Id);
                db.VEHICULO.Attach(oVehiculo);
                db.VEHICULO.Remove(oVehiculo);

                db.SaveChanges();

                return Content("1");
            }
        }
    }
}

mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Carros'nt", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse" >
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Registrar", "Index", "Vehiculo")</li>
                </ul>
                <ul class= "nav navbar-nav" style="float:right;">
                    <li>@Html.ActionLink("Cerrar Sesion", "Logoff", "Cerrar")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

mvc/Views/Shared/_LayoutAcceso.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="fondo">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Carros'nt", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scriptsAcceder", required: false)
</body>
</html>